version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: bumbiro_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      # Docker pulls these dynamically from your .env file
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - bumbiro_pgdata:/var/lib/postgresql/data

volumes:
  bumbiro_pgdata: