import os
import sys

import pytest
from fastapi.testclient import TestClient

# Ensure the repo root is importable during pytest run
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from app.api.main import app as fastapi_app

# Application fixture
@pytest.fixture(scope="session")
def test_client():
    """FastAPI TestClient fixture for integration tests."""
    return TestClient(fastapi_app)


# Dependency override fixture
@pytest.fixture(autouse=True)
def dependency_overrides(monkeypatch):
    """Override external dependencies to avoid real network/API calls."""
    # The app currently uses get_rag_pipeline in routes via Depends.
    # Ensure no actual model/embedding calls are made in integration tests.
    # TODO: implement explicit override when concrete pipeline interface is well-defined.
    yield


# Mocked data fixtures
@pytest.fixture
def constitutional_documents():
    """Mocked constitutional documents for retrieval tests."""
    return [
        {
            "page_content": "Section 67: political rights of citizens...",
            "metadata": {"source": "Zimbabwe Constitution"},
        }
    ]


@pytest.fixture
def retrieved_contexts():
    """Mocked retrieved context strings for RAG pipeline tests."""
    return [
        "The Constitution may be amended by ...",
    ]


@pytest.fixture
def generated_responses():
    """Mocked responses generated by the model."""
    return "The amendment process is ..."


# Mocked component fixtures
@pytest.fixture
def mocked_retriever():
    """A simple mock retriever object to avoid embedding/vector calls."""
    class MockRetriever:
        def retrieve(self, query):
            return [
                type("Doc", (), {"page_content": "Mocked context piece", "metadata": {"source": "dummy"}})()
            ]

    return MockRetriever()


@pytest.fixture
def mocked_generator():
    """A simple mock generator object to avoid LLM calls."""
    class MockGenerator:
        def generate(self, prompt):
            return "Mocked answer based on prompt"

    return MockGenerator()
